import {DAY,lastEvent,cycles,predict,record,duration,status,initial,validate} from './core.js';
import {calendarEvents,toICS} from './calendar.js';
const KEY='juicelog.v1',app=document.querySelector('#app'),modal=document.querySelector('#modal');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=t=>new Date(t).toLocaleDateString('zh-CN',{month:'short',day:'numeric'});
const stamp=t=>new Date(t).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const range=p=>`${date(p.low)} – ${date(p.high)}`;
let data=initial(),filter='all',undo=null,timer,loadError=false,selectedIcon='🎧';
try{const raw=localStorage.getItem(KEY);if(raw)data=validate(JSON.parse(raw));}catch{loadError=true;}
function save(next){try{if(loadError)throw Error();localStorage.setItem(KEY,JSON.stringify(next));data=next;render();return true;}catch{toast('无法保存。请允许浏览器储存，或先导出原始数据。');return false;}}
function mutate(fn){const next=structuredClone(data);fn(next);return save(next);}
function toast(message,canUndo=false){clearTimeout(timer);const el=document.querySelector('#toast');el.innerHTML=`${esc(message)}${canUndo?'<button data-action="undo">撤销</button>':''}`;el.className='show';timer=setTimeout(()=>{el.className='';},canUndo?15000:5000);}
function device(){return data.devices.find(d=>d.id===decodeURIComponent(location.hash.slice(8)));}
function actions(d){const t=lastEvent(d)?.type;return `<div class="actions"><button data-action="record" data-id="${d.id}" data-type="empty" ${t==='empty'?'disabled':''}>🪫 没电了</button><button data-action="record" data-id="${d.id}" data-type="charged" ${t==='charged'?'disabled':''}>🔋 充好了</button></div>`;}
function card(d){const s=status(d),p=predict(d),last=lastEvent(d);const fill=p?Math.max(4,Math.min(100,(1-(Date.now()-last.at)/p.mean)*100)):s.kind==='empty'?4:s.kind==='new'?0:65;return `<article class="card"><div class="card-head"><span class="device-icon">${esc(d.icon)}</span><button class="device-link" data-action="detail" data-id="${d.id}"><h3>${esc(d.name)}</h3><span class="muted">${cycles(d).length} 次完整续航</span></button><span class="chevron" aria-hidden="true">›</span></div><div class="state ${s.kind}">${s.label}</div><div class="muted">${p?`预计补电 ${range(p)}`:s.sub}</div><div class="track ${s.kind}" aria-hidden="true"><span style="width:${fill}%"></span></div><div class="card-meta">${last?`上次${last.type==='charged'?'充好':'没电'} · ${stamp(last.at)}`:'还没有记录，从今天开始吧'}<br>${p?'进度为时间估算，并非实时电量':''}</div>${actions(d)}<div class="card-bottom"><button class="text" data-action="detail" data-id="${d.id}">续航时间轴</button><button class="text" data-action="calendar" data-id="${d.id}" ${!p&&!(data.settings.history&&d.events.length)?'disabled':''}>＋ 日历</button></div></article>`;}
function home(){const need=data.devices.filter(d=>status(d).rank<=1),pred=data.devices.filter(d=>predict(d));const list=[...(filter==='soon'?need:data.devices)].sort((a,b)=>status(a).rank-status(b).rank);return `<div class="eyebrow">YOUR EVERYDAY ENERGY</div><div class="heading"><div><h1>我的东西，还能撑多久？</h1><p class="muted">${new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})} · 把充电这件小事交给记录。</p></div><button class="primary" data-action="add">＋ 添加设备</button></div><section class="summary"><div><div class="eyebrow">ENERGY CHECK</div><h2>${need.length?`${need.length} 件小东西，等你补补电。`:data.devices.length?'今天，少一件需要惦记的事。':'从第一件小东西开始。'}</h2><p class="muted">${need.length?need.map(d=>esc(d.name)).join('、'):'用完点一下，充好点一下。剩下的慢慢了解。'}</p></div><div class="stats"><div class="stat"><strong>${need.length.toString().padStart(2,'0')}</strong><span>最近该充</span></div><div class="stat"><strong>${data.devices.length.toString().padStart(2,'0')}</strong><span>我的设备</span></div><div class="stat"><strong>${pred.length.toString().padStart(2,'0')}</strong><span>已有预测</span></div></div></section><div class="section-head"><h2>我的设备 <span class="muted">${data.devices.length}</span></h2><div class="tabs" aria-label="筛选设备"><button data-action="filter" data-filter="all" class="${filter==='all'?'active':''}" aria-pressed="${filter==='all'}">全部</button><button data-action="filter" data-filter="soon" class="${filter==='soon'?'active':''}" aria-pressed="${filter==='soon'}">最近该充</button></div></div>${list.length?`<div class="grid">${list.map(card).join('')}</div>`:`<section class="empty-box"><div class="big">${data.devices.length?'☀️':'🔋'}</div><h2>${data.devices.length?'暂时没有需要补电的设备':'第一件，想记住谁？'}</h2><p class="muted">${data.devices.length?'随时记录真实状态，预测会跟着你一起成长。':'选择一个常用设备，或者添加自己的。'}</p>${!data.devices.length?'<div class="suggestions">'+[['🎧','AirPods'],['✏️','Apple Pencil'],['🔋','充电宝'],['📷','相机']].map(([icon,name])=>`<button data-action="preset" data-name="${name}" data-icon="${icon}">${icon} ${name} ＋</button>`).join('')+'</div>':''}</section>`}<aside class="note"><span>✦</span><div><b>越记录，越懂你的使用习惯。</b> 完成 3 轮续航后，开始预测下次补电日期。估算仅参考你的记录。</div></aside>`;}
function detail(d){const p=predict(d),cs=cycles(d),s=status(d);return `<button class="text" data-action="home">返回我的设备</button><div class="detail-top"><span class="device-icon">${esc(d.icon)}</span><div><h1>${esc(d.name)}</h1><span class="muted">每一轮续航，都有迹可循。</span></div><button class="quiet" data-action="edit" data-id="${d.id}">管理设备</button></div><div class="detail-layout"><section class="panel"><div class="eyebrow">NEXT RECHARGE</div><div class="state ${s.kind}">${s.label}</div><div class="prediction">${p?range(p):'还在认识它'}</div><p class="muted">${p?`最近 ${p.count} 轮加权估算 · 越近期权重越高`:`${cs.length}/3 轮完整续航，暂不猜日期`}</p>${actions(d)}<button class="primary full" data-action="calendar" data-id="${d.id}" ${!p&&!(data.settings.history&&d.events.length)?'disabled':''}>＋ 添加到日历</button><p class="muted">${p?'导出预测日期区间；系统日历确认后生效。':'再积累一些记录，就能安排补电提醒。'}</p>${d.events.length?`<button class="text muted" data-action="undo-last" data-id="${d.id}">撤销最近一次记录</button>`:''}</section><section class="panel"><div class="section-head"><h2>续航时间轴</h2><span class="muted">${cs.length} 轮</span></div>${cs.length?`<div class="timeline" tabindex="0" aria-label="横向滚动查看完整续航">${cs.slice().reverse().map((c,i)=>`<div class="cycle"><span class="muted">第 ${cs.length-i} 轮</span><strong>${duration(c.duration)}</strong><div class="muted">🔋 ${stamp(c.start)}<br>🪫 ${stamp(c.end)}</div></div>`).join('')}</div>`:'<div class="empty-history">充好到下一次没电，会在这里连成一段续航。</div>'}<h3 class="details-title">最近记录</h3>${d.events.length?d.events.slice().reverse().map(e=>`<div class="event"><span>${e.type==='charged'?'🔋 充好了':'🪫 没电了'}</span><time>${stamp(e.at)}</time></div>`).join(''):'<p class="muted">还没有记录。点一次「充好了」开始。</p>'}</section></div>`;}
function render(){app.innerHTML=loadError?'<section class="empty-box"><h1>暂时无法读取本地数据</h1><p>原始数据没有被覆盖。请先在设置中导出原始备份，再恢复有效备份。</p><button class="primary" data-action="settings">打开设置</button></section>':location.hash.startsWith('#device/')&&device()?detail(device()):home();}
function open(content){modal.innerHTML=content;if(!modal.open)modal.showModal();}
const head=title=>`<div class="dialog-head"><h2>${title}</h2><button class="close" data-action="close" aria-label="关闭">×</button></div>`;
function editor(d=null,name='',icon='🎧'){selectedIcon=d?.icon||icon;open(`${head(d?'管理设备':'添加一件小东西')}<form id="device-form" data-id="${d?.id||''}"><label for="device-name">设备名称</label><input id="device-name" name="name" maxlength="40" required value="${esc(d?.name||name)}" placeholder="比如：随身的 AirPods" autocomplete="off"><label>选一个图标</label><div class="icons">${['🎧','✏️','🔋','📷','⌨️','🖱️','⌚','🎮','💡','📱'].map(i=>`<button type="button" data-action="icon" data-icon="${i}" aria-label="图标 ${i}" aria-pressed="${i===selectedIcon}" class="${i===selectedIcon?'selected':''}">${i}</button>`).join('')}</div><div class="form-actions">${d?`<button type="button" class="danger" data-action="delete" data-id="${d.id}">删除设备</button>`:''}<button class="primary" type="submit">${d?'保存修改':'添加设备'}</button></div></form>`);}
function settings(){open(`${head('设置与日历')}<label for="lead">日历提前提醒</label><select id="lead">${[0,1,2].map(n=>`<option value="${n}" ${data.settings.lead===n?'selected':''}>${n?`提前 ${n} 天`:'当天'}</option>`).join('')}</select><label class="check"><input id="history" type="checkbox" ${data.settings.history?'checked':''}>导出日历时包含实际历史记录</label><p class="muted">历史默认为关。提醒以预测区间第一天为基准；具体通知时间由日历应用决定。</p><p class="muted">ICS 需要你在系统日历确认导入，不会自动同步。重新预测后，请删除旧预测再导入，避免重复提醒。</p><div class="setting-section"><h3>数据在你手里</h3><p class="muted">仅保存在当前浏览器；清除网站数据会丢失记录。换设备前请备份。</p><button class="quiet" data-action="backup">导出${loadError?'原始':''}备份</button> <button class="quiet" data-action="import">恢复备份</button><input id="import-file" type="file" accept="application/json,.json" hidden></div><div class="setting-section"><h3>放到手机主屏幕</h3><p class="muted">iPhone：Safari 分享 → 添加到主屏幕。Android：浏览器菜单 → 安装应用。首次访问后可离线记录。</p></div><div class="form-actions"><button class="primary" data-action="save-settings">保存设置</button></div>`);}
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function addRecord(id,type){const d=data.devices.find(x=>x.id===id);if(!d)return;const before=structuredClone(d.events);try{let changed=false;const ok=mutate(next=>{changed=record(next.devices.find(x=>x.id===id),type);});if(ok&&changed){undo={id,before};toast(`${d.name} · 已记下${type==='charged'?'充好':'没电'}时间`,true);}}catch(e){toast(e.message);}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id,d=data.devices.find(x=>x.id===id);if(a==='home')location.hash='home';if(a==='detail')location.hash='device/'+id;if(a==='add')editor();if(a==='preset')editor(null,b.dataset.name,b.dataset.icon);if(a==='edit'&&d)editor(d);if(a==='close')modal.close();if(a==='settings')settings();if(a==='filter'){filter=b.dataset.filter;render();}if(a==='record')addRecord(id,b.dataset.type);if(a==='icon'){selectedIcon=b.dataset.icon;modal.querySelectorAll('[data-action=icon]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});}if(a==='undo'&&undo){const u=undo;if(mutate(next=>{const target=next.devices.find(x=>x.id===u.id);if(target)target.events=u.before;})){undo=null;toast('已撤销记录');}}if(a==='undo-last'&&d){open(`${head('撤销最近一次记录？')}<p>${esc(d.name)} · ${stamp(lastEvent(d).at)}</p><p class="muted">续航和预测会一并重新计算。</p><div class="form-actions"><button class="quiet" data-action="close">取消</button><button class="primary" data-action="confirm-undo" data-id="${id}">确认撤销</button></div>`);}if(a==='confirm-undo'){if(mutate(next=>next.devices.find(x=>x.id===id).events.pop())){undo=null;modal.close();toast('已撤销最近记录');}}if(a==='delete'&&d)open(`${head('删除这个设备？')}<p>「${esc(d.name)}」的所有历史记录也会删除。</p><div class="form-actions"><button class="quiet" data-action="close">取消</button><button class="danger" data-action="confirm-delete" data-id="${id}">确认删除</button></div>`);if(a==='confirm-delete'){if(mutate(next=>{next.devices=next.devices.filter(x=>x.id!==id);})){undo=null;modal.close();location.hash='home';}}if(a==='calendar'&&d){const events=calendarEvents(d,data.settings);if(!events.length)return toast('积累 3 轮续航后可导出预测');download(toICS(events),'JuiceLog.ics','text/calendar;charset=utf-8');toast('已生成日历文件，请打开并确认导入');}if(a==='save-settings'){if(mutate(next=>{next.settings={lead:Number(document.querySelector('#lead').value),history:document.querySelector('#history').checked};}))modal.close();}if(a==='backup'){let raw;try{raw=loadError?localStorage.getItem(KEY):JSON.stringify(data,null,2);}catch{return toast('浏览器禁止读取储存');}download(raw||'{}','JuiceLog-backup.json','application/json');}if(a==='import')document.querySelector('#import-file').click();});
document.addEventListener('submit',e=>{if(e.target.id!=='device-form')return;e.preventDefault();const name=new FormData(e.target).get('name').trim();if(!name)return;const id=e.target.dataset.id;if(mutate(next=>{if(id){const d=next.devices.find(x=>x.id===id);d.name=name;d.icon=selectedIcon;}else next.devices.push({id:crypto.randomUUID(),name,icon:selectedIcon,events:[]});})){modal.close();toast(id?'设备已更新':'设备已添加，充好后点一下开始');}});
let pendingImport;
document.addEventListener('change',async e=>{if(e.target.id!=='import-file'||!e.target.files[0])return;try{if(e.target.files[0].size>5e6)throw Error('备份文件过大');pendingImport=validate(JSON.parse(await e.target.files[0].text()));open(`${head('恢复备份？')}<p>将用备份中的 ${pendingImport.devices.length} 个设备替换当前数据。建议先导出当前备份。</p><div class="form-actions"><button class="quiet" data-action="close">取消</button><button id="confirm-import" class="primary">确认恢复</button></div>`);document.querySelector('#confirm-import').onclick=()=>{const oldError=loadError;loadError=false;if(save(pendingImport)){undo=null;modal.close();location.hash='home';toast('备份已恢复');}else loadError=oldError;};}catch(err){toast('无法恢复：'+err.message);}});
window.addEventListener('hashchange',render);window.addEventListener('storage',e=>{if(e.key===KEY){try{data=e.newValue?validate(JSON.parse(e.newValue)):initial();loadError=false;undo=null;render();}catch{loadError=true;render();}}});document.addEventListener('visibilitychange',()=>{if(!document.hidden)render();});
render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>toast('离线模式暂不可用，联网时仍可记录'));
