import {predict,DAY} from './core.js';
const escape=s=>s.replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');
const utc=t=>new Date(t).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');
const date=t=>{const d=new Date(t);return `${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;};
function fold(s){let out='',line='',size=0;for(const c of s){const n=new TextEncoder().encode(c).length;if(size+n>75){out+=line+'\r\n';line=' ';size=1;}line+=c;size+=n;}return out+line;}
export function calendarEvents(device,settings,now=Date.now()){const p=predict(device),events=[];if(p){const start=Math.max(p.low,now);const end=new Date(Math.max(p.high,start));end.setDate(end.getDate()+1);events.push({uid:`prediction-${device.id}-${device.events.at(-1).id}@juicelog`,start:date(start),end:date(end),allDay:true,title:`${device.name} · 预计需要充电`,description:'这是日期区间估算，不是电量检测。ICS 不会自动更新；预测变化后请删除旧事件并重新导入。',lead:settings.lead});}if(settings.history){for(const e of device.events)events.push({uid:`actual-${e.id}@juicelog`,start:utc(e.at),end:utc(e.at+60000),allDay:false,title:`${device.name} · ${e.type==='charged'?'充好了':'没电了'}`,description:'实际点击记录时间；不代表充电过程的开始或结束。'});}return events;}
export function toICS(events,now=Date.now()){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//JuiceLog//Charging diary//ZH','CALSCALE:GREGORIAN'];for(const e of events){lines.push('BEGIN:VEVENT',`UID:${e.uid}`,`DTSTAMP:${utc(now)}`,`DTSTART${e.allDay?';VALUE=DATE':''}:${e.start}`,`DTEND${e.allDay?';VALUE=DATE':''}:${e.end}`,`SUMMARY:${escape(e.title)}`,`DESCRIPTION:${escape(e.description)}`);if(e.lead!==undefined)lines.push('BEGIN:VALARM',`TRIGGER:${e.lead?`-P${e.lead}D`:'PT0S'}`,'ACTION:DISPLAY',`DESCRIPTION:${escape(e.title)}`,'END:VALARM');lines.push('END:VEVENT');}lines.push('END:VCALENDAR');return lines.map(fold).join('\r\n')+'\r\n';}
// Future provider contract: sync(events, { deviceId, previousEventIds }) -> remote IDs.
// ICS is deliberately an export provider; it cannot update or delete imported events.
export const icsProvider={export: (device,settings)=>toICS(calendarEvents(device,settings))};
