export const DAY=86400000;
export const lastEvent=d=>d.events.at(-1);
export function cycles(d){let start=null;const out=[];for(const e of d.events){if(e.type==='charged')start=e;else if(start){if(e.at>start.at)out.push({start:start.at,end:e.at,duration:e.at-start.at,id:e.id});start=null;}}return out;}
export function predict(d){const sample=cycles(d).slice(-5);const last=lastEvent(d);if(sample.length<3||last?.type!=='charged')return null;const weight=sample.reduce((n,_,i)=>n+i+1,0);const mean=sample.reduce((n,c,i)=>n+c.duration*(i+1),0)/weight;const variance=sample.reduce((n,c,i)=>n+(c.duration-mean)**2*(i+1),0)/weight;const spread=Math.max(DAY*.5,mean*.15,Math.sqrt(variance));return{mean,low:last.at+Math.max(mean*.2,mean-spread),high:last.at+mean+spread,count:sample.length};}
export function record(d,type,at=Date.now()){if(!['charged','empty'].includes(type))throw Error('无效记录');if(lastEvent(d)?.type===type)return false;if(lastEvent(d)?.at>=at)throw Error('设备时间异常，请检查系统时间');d.events.push({id:crypto.randomUUID(),type,at});return true;}
export function duration(ms){if(ms<60000)return '不到 1 分钟';if(ms<3600000)return `${Math.floor(ms/60000)} 分钟`;const days=ms/DAY;return days>=1?`${Number(days.toFixed(1))} 天`:`${Math.max(1,Math.round(ms/3600000))} 小时`;}
export function status(d,now=Date.now()){const last=lastEvent(d),p=predict(d);if(last?.type==='empty')return{label:'该充电啦',sub:'充好后，点一下就记住',kind:'empty',rank:0};if(!last)return{label:'等你第一次记录',sub:'充满后点「充好了」开始',kind:'new',rank:3};if(!p)return{label:'正在了解它',sub:`已完成 ${cycles(d).length}/3 轮 · 再用一阵就能预测`,kind:'learning',rank:2};if(now>=p.low)return{label:now>p.high?'可能已经该充了':'最近该充电了',sub:'按你的使用习惯，记得补电',kind:'soon',rank:1};return{label:`大约还能用 ${duration(p.low-now)}起`,sub:'根据最近几轮使用习惯估算',kind:'good',rank:2};}
export const initial=()=>({version:1,devices:[],settings:{lead:1,history:false}});
export function validate(data){if(data?.version!==1||!Array.isArray(data.devices)||!data.settings||![0,1,2].includes(data.settings.lead)||typeof data.settings.history!=='boolean')throw Error('备份格式不正确');const ids=new Set();for(const d of data.devices){if(typeof d.id!=='string'||!(/^[a-zA-Z0-9-]{1,80}$/).test(d.id)||ids.has(d.id)||typeof d.name!=='string'||!d.name.trim()||d.name.length>40||typeof d.icon!=='string'||d.icon.length>12||!Array.isArray(d.events))throw Error('设备数据不正确');ids.add(d.id);let prev=0,type=null;const eventIds=new Set();for(const e of d.events){if(typeof e.id!=='string'||!(/^[a-zA-Z0-9-]{1,80}$/).test(e.id)||eventIds.has(e.id)||!['charged','empty'].includes(e.type)||e.type===type||!Number.isFinite(e.at)||e.at<=prev||e.at>Date.now()+60000)throw Error('历史记录不正确');eventIds.add(e.id);prev=e.at;type=e.type;}}return data;}
